;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		ess-smart-comma
		keyboard-quit
		mouse-set-region
		suspend-frame
		))

(setq mc/cmds-to-run-once
      '(
		noweb-mouse-first-button
		))
